export const GET_EMPLOYEES_LIST_SUCCESS = 'GET_EMPLOYEES_LIST_SUCCESS';
export const GET_EMPLOYEES_LIST_ISLOADING = 'GET_EMPLOYEES_LIST_ISLOADING';

export const GET_EMPLOYEES_REVIEW_ISLOADING = 'GET_EMPLOYEES_REVIEW_ISLOADING';
export const GET_EMPLOYEES_REVIEW_SUCCESS = 'GET_EMPLOYEES_REVIEW_SUCCESS';

export const CREATE_EMPLOYEE_SUCCESS = 'CREATE_EMPLOYEE_SUCCESS';
export const CREATE_EMPLOYEE_ERROR = 'CREATE_EMPLOYEE_ERROR';
export const DELETE_CREATE_EMPLOYEE_ERROR = 'DELETE_CREATE_EMPLOYEE_ERROR';
export const CREATE_EMPLOYEE_ERROR_ISLOADING = 'CREATE_EMPLOYEE_ERROR_ISLOADING';

export const CREATE_REVIEW_SUCCESS = 'CREATE_REVIEW_SUCCESS';
export const CREATE_REVIEW_ERROR = 'CREATE_REVIEW_ERROR';
export const DELETE_CREATE_REVIEW_ERROR = 'DELETE_CREATE_REVIEW_ERROR';
export const CREATE_REVIEW_ERROR_ISLOADING = 'CREATE_REVIEW_ERROR_ISLOADING';

export const DELETE_REVIEW = 'DELETE_REVIEW';
export const DELETE_REVIEW_ISLOADING = 'DELETE_REVIEW_ISLOADING';

export const CREATE_ADMIN_SUCCESS = 'CREATE_ADMIN_SUCCESS';
export const CREATE_ADMIN_ERROR = 'CREATE_ADMIN_ERROR';
export const DELETE_CREATE_ADMIN_ERROR = 'DELETE_CREATE_ADMIN_ERROR';
export const CREATE_ADMIN_ERROR_ISLOADING = 'CREATE_ADMIN_ERROR_ISLOADING';

export const LOGIN_ADMIN_SUCCESS = 'LOGIN_ADMIN_SUCCESS';
export const LOGIN_ADMIN_ERROR = 'LOGIN_ADMIN_ERROR';
export const DELETE_LOGIN_ADMIN_ERROR = 'DELETE_LOGIN_ADMIN_ERROR';
export const LOGIN_ADMIN_ERROR_ISLOADING = 'LOGIN_ADMIN_ERROR_ISLOADING';

export const LOGOUT_USER = 'LOGOUT_USER';

export const CREATE_FEEDBACK_SUCCESS = 'CREATE_FEEDBACK_SUCCESS';
export const CREATE_FEEDBACK_ERROR = 'CREATE_FEEDBACK_ERROR';
export const DELETE_CREATE_FEEDBACK_ERROR = 'DELETE_CREATE_FEEDBACK_ERROR';
export const CREATE_FEEDBACK_ERROR_ISLOADING = 'CREATE_FEEDBACK_ERROR_ISLOADING';
